import java.awt.event.KeyEvent;

public class Snake_Main extends javax.swing.JFrame {
    //private RunSnake run_snake;
    /** Creates new form Snake_Main */
    public Snake_Main() {
        initComponents();
        jpanel_main.SetScoreLabel(score_label);
    }

    /** This method is called from within the constructor to
     * initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is
     * always regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        score_label = new javax.swing.JLabel();
        jpanel_main = new SnakePanel();
        menu_main = new javax.swing.JMenuBar();
        menu_file = new javax.swing.JMenu();
        menu_go = new javax.swing.JMenu();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        score_label.setFont(new java.awt.Font("Tahoma", 0, 24)); // NOI18N
        score_label.setText("SCORE: ");

        javax.swing.GroupLayout jpanel_mainLayout = new javax.swing.GroupLayout(jpanel_main);
        jpanel_main.setLayout(jpanel_mainLayout);
        jpanel_mainLayout.setHorizontalGroup(
            jpanel_mainLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 0, Short.MAX_VALUE)
        );
        jpanel_mainLayout.setVerticalGroup(
            jpanel_mainLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 284, Short.MAX_VALUE)
        );

        menu_file.setText("File");
        menu_main.add(menu_file);

        menu_go.setLabel("Go");
        menu_main.add(menu_go);

        setJMenuBar(menu_main);

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(237, 237, 237)
                .addComponent(score_label)
                .addContainerGap(355, Short.MAX_VALUE))
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jpanel_main, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addContainerGap())
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jpanel_main, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(score_label, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );

        score_label.getAccessibleContext().setAccessibleName("");

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void jpanel_mainKeyPressed(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_jpanel_mainKeyPressed
        
        int keyCode = evt.getKeyCode();
        
        switch( keyCode ) {
            case KeyEvent.VK_UP:
                if(jpanel_main.GetDirection() == Direction.UP) //Do nothing if same direction (Solved speeding up the snake by holding down a direction key
                    return;                
                jpanel_main.ChangeDirection(Direction.UP);
                break;

            case KeyEvent.VK_DOWN:
                if(jpanel_main.GetDirection() == Direction.DOWN)
                    return;
                jpanel_main.ChangeDirection(Direction.DOWN);
                break;

            case KeyEvent.VK_RIGHT:
                if(jpanel_main.GetDirection() == Direction.RIGHT)
                    return;
                jpanel_main.ChangeDirection(Direction.RIGHT);
                break;

            case KeyEvent.VK_LEFT:
                if(jpanel_main.GetDirection() == Direction.LEFT)
                    return;
                jpanel_main.ChangeDirection(Direction.LEFT);
                break;
        }
        jpanel_main.stop();
        jpanel_main.start();

    }//GEN-LAST:event_jpanel_mainKeyPressed

    private void jpanel_mainMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jpanel_mainMouseClicked
        // TODO add your handling code here:
        jpanel_main.requestFocusInWindow();
    }//GEN-LAST:event_jpanel_mainMouseClicked

    /**
    * @param args the command line arguments
    */
    public static void main(String args[]) {
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new Snake_Main().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private SnakePanel jpanel_main;
    private javax.swing.JMenu menu_file;
    private javax.swing.JMenu menu_go;
    private javax.swing.JMenuBar menu_main;
    private javax.swing.JLabel score_label;
    // End of variables declaration//GEN-END:variables

}